### PR TITLE
MVP done. 

### PR DESCRIPTION
**Pull request by MFalahee**
I left out the icons but I've styled everything to be relatively close to the design files. All functionality works as well, with some PropType checking in relevant spots.

### CODE REVIEW

**Comment by MFalahee** [comment]
Day 2: Got MVP done. Styled website and added icons. Functionality works!

**Comment by MFalahee** [comment]
Day 3, HOC 'authentication' is working properly, and I managed to finish a stretch today by using the logged-in username for comments as well.

**Comment by MFalahee** [comment]
MVP for day four is done as far as I can tell. I've refactored out all of my css in favor of using styled components. My styling in general is still a little janky in comparison to the design file.

**Review by ghost — APPROVED** [review]
Grade 2

**Pull request merged**
